services:
  webhook:
    image: ghcr.io/muava12/webhook-to-rabbitmq:latest
    container_name: webhook-service
    ports:
      - 8001:8001
    environment:
      - WEBHOOK_PORT=8001
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=gowa
      - RABBITMQ_PASSWORD=mantab
      - RABBITMQ_VHOST=/
      - EXCHANGE_NAME=gowa
      - BUFFER_DIR=/buffer
      - SAVE_DIR=/data
      - RMQ_MGMT_URL=http://rabbitmq:15672
      - RMQ_MGMT_USER=n8n
      - RMQ_MGMT_PASSWORD=mantab
      - NTFY_URL=https://ntfy.sh/monitor-server-30AhxaPwq00MzspW
      - TZ=Asia/Jakarta
    volumes:
      - ./buffer:/buffer
      - ./data:/data
    networks:
      - cloudflared-net
    restart: unless-stopped

networks:
  cloudflared-net:
    external: true
